export { default as Container } from './src/container.vue'
export { default as Aside } from './src/aside.vue'
export { default as Footer } from './src/footer.vue'
export { default as Header } from './src/header.vue'
export { default as Main } from './src/main.vue'
