export declare const isServer: boolean;
export declare const isBool: (val: unknown) => boolean;
export declare const isObject: (value: any) => boolean;
export declare const isNull: (value: any) => boolean;
export declare const isUndefined: (value: any) => boolean;
export declare const isSupportObjectFit: () => boolean;
export declare const isHtmlEle: (e: HTMLElement) => boolean;
export declare const isFirefox: () => boolean;
export declare const isIE: () => boolean;
export declare const isEdge: () => boolean;
export declare function isKorean(text: string): boolean;
