name: Deploy Github doc
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Docs
        run: yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: dist
          GIT_CONFIG_NAME: shlroland
          GIT_CONFIG_EMAIL: shlroland1995@gmail.com
          COMMIT_MESSAGE: website deploy
