name: Deploy Github doc
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Docs
        run: yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: shlroland
          GIT_CONFIG_EMAIL: shlroland1995@gmail.com
          COMMIT_MESSAGE: website deploy
  sync-to-gitee:
    needs: deploy-docs
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:shlroland/rol-ui-vue3.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:shlroland/rol-ui-vue3.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: shlroland
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: shlroland/rol-ui-vue3
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
